//Object mapping the form fields to worksheet columns
exports.fieldPositions = {
  id: "A",
  productName: "B",
  productDesc: "C",
  productType: "D",
  productURL: "E",
  productImg: "F",
  imageConfirm: "G",
  productTags: "H",
  productDomain: "I",
  stakeholderName: "J",
  productPII: "K",
  piiExplanation: "L",
  sampleFields: "M",
  sampleValues: "N",
  fulfillmentGroup: "O",
  otherDesc: "P",
}

exports.fieldValidations = [
  { field: "productName", size: 0 },
  { field: "productDesc", size: 60 },
  { field: "productType", size: 0, includes: this.types },
  { field: "productTags", size: 0 },
  { field: "productDomain", size: 0, includes: this.domains },
  { field: "stakeholderName", size: 0 },
  { field: "productPII", size: 0, dependent: { field: "piiExplanation", size: 0 }, dependentValue: "true" },
  { field: "sampleFields", size: 0 },
  { field: "sampleValues", size: 0 },
  { field: "fulfillmentGroup", size: 10 },
  { field: "requesterName", size: 0 },
  { field: "requesterMail", size: 0 },
  { field: "requesterID", size: 0 },
]

exports.humanReadableFields = {
  id: "ID",
  productName: "Product Name",
  productDesc: "Product Description",
  productType: "Product Type",
  productURL: "Product URL",
  productImg: "Product Image",
  imageConfirm: "Image Confirm",
  productTags: "Product Tags",
  productDomain: "Product Domain",
  stakeholderName: "Stakeholder Name",
  productPII: "Product Contains PII",
  piiExplanation: "PII Explanation",
  sampleFields: "Same Fields",
  sampleValues: "Sample Values",
  fulfillmentGroup: "Fulfillment Group",
  requesterName: "Requester Name",
  requesterMail: "Requester Mail",
  requesterID: "Requester ID",
}

exports.types = [
  "Report",
  "Dashboard",
  "Data Science Model",
  "Dataset",
  "Webservice (API)",
]

exports.domains = [
  "Customer",
  "Digital Assets",
  "Distributor/Region/Dealer",
  "Facilities",
  "Finance Management and Accounting",
  "Human Resources",
  "Identity and Access Management",
  "Manufacturing",
  "Manufacturing Parts",
  "Marketing",
  "Quality",
  "Research and Development",
  "Service History",
  "Service Parts and Accessories",
  "Social Media",
  "Survey",
  "Telematics",
  "Vehicle",
  "Warranty",
]